[package]
name = "projetario"
version.workspace = true
edition.workspace = true

[features]
dockerimgb = ["openssl/vendored"]
test-utils = ["dominio/test-utils"]

[workspace]
members = ["comum", "config", "db_seeder", "dominio", "sessions"]
package.version = "0.1.0"
package.edition = "2024"

[workspace.dependencies]
comum.path = "comum"
dominio.path = "dominio"
inertia-sessions.path = "sessions"
config.path = "config"
actix-files = "0.6.10"
actix-session = "0.11.0"
actix-web = "4.13.0"
anyhow = "1.0.102"
async-trait = "0.1.89"
inertia-rust = { version = "2.4.6", features = [
    "actix",
    "vite-hbs-template-resolver",
    "actix-validator",
] }
tokio = { version = "1.50.0", features = [
    "fs",
    "io-std",
    "rt",
    "rt-multi-thread",
    "macros",
] }
vite-rust = "0.2"
log = "0.4.27"
serde = "1.0.228"
serde_json = "1.0.149"
rand = "0.10.0"
chrono = { version = "0.4.44", features = ["serde"] }
pretty_assertions = "1.4.1"
dotenvy = "0.15.7"
env_logger = "0.11.8"
futures-util = "0.3.32"
thiserror = "2.0.18"
rstest = "0.26.1"
sqlx = { version = "0.8.6", features = [
    "runtime-tokio",
    "tls-rustls-ring-native-roots",
    "postgres",
    "derive",
    "migrate",
    "chrono",
    "uuid",
] }
pbkdf2 = { version = "0.12", features = ["simple"] }
base64 = { version = "0.22", features = ["std"] }
uuid = { version = "1.22.0", features = ["v4", "serde"] }
url = "2.5.8"
derive_builder = "0.20.2"
proptest = "1.10.0"
proptest-arbitrary-interop = "0.1.0"
fake = { version = "4.4.0", features = ["derive", "chrono", "url"] }

[dependencies]
dominio.workspace = true
comum.workspace = true
config.workspace = true
inertia-sessions.workspace = true
vite-rust.workspace = true
actix-files.workspace = true
actix-session.workspace = true
inertia-rust.workspace = true
async-trait.workspace = true
env_logger.workspace = true
actix-web.workspace = true
uuid.workspace = true
chrono.workspace = true
anyhow.workspace = true
dotenvy.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
futures-util.workspace = true
sqlx.workspace = true
validator = { version = "0.20", features = ["derive"] }
openssl = { version = "0.10.73", optional = true }
pbkdf2.workspace = true
tokio.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
rstest.workspace = true
tokio = { workspace = true, features = ["test-util"] }
db_seeder = { path = "db_seeder" }
