[package]
name = "projetario"
version.workspace = true
edition.workspace = true

[features]
dockerimgb = ["openssl/vendored"]
test-utils = ["dominio/test-utils"]

[workspace]
members = ["build_utils", "comum", "config", "db_seeder", "dominio", "sessions"]
package.version = "0.1.0"
package.edition = "2024"

[workspace.dependencies]
build-utils.path = "build_utils"
comum.path = "comum"
dominio.path = "dominio"
inertia-sessions.path = "sessions"
config.path = "config"
actix-files = "0.6.6"
actix-session = "0.10.1"
actix-web = "4.11.0"
anyhow = "1.0.98"
async-trait = "0.1.88"
inertia-rust = { version = "2.4.3", features = [
    "actix",
    "vite-hbs-template-resolver",
    "actix-validator",
] }
tokio = { version = "1.45.0", features = [
    "fs",
    "io-std",
    "rt",
    "rt-multi-thread",
    "macros",
] }
vite-rust = "0.2"
log = "0.4.27"
serde = "1.0.219"
serde_json = "1.0.140"
rand = "0.9.1"
chrono = { version = "0.4.41", features = ["serde"] }
pretty_assertions = "1.4.1"
dotenvy = "0.15.7"
env_logger = "0.11.8"
futures-util = "0.3.31"
thiserror = "2.0.12"
rstest = "0.25.0"
sqlx = { version = "0.8.5", features = [
    "runtime-tokio",
    "tls-rustls-ring-native-roots",
    "postgres",
    "derive",
    "migrate",
    "chrono",
    "uuid",
] }
pbkdf2 = { version = "0.12", features = ["simple"] }
base64 = { version = "0.22", features = ["std"] }
uuid = { version = "1.17.0", features = ["v4", "serde"] }
url = "2.5.4"

[dependencies]
dominio.workspace = true
comum.workspace = true
config.workspace = true
inertia-sessions.workspace = true
vite-rust.workspace = true
actix-files.workspace = true
actix-session.workspace = true
inertia-rust.workspace = true
async-trait.workspace = true
env_logger.workspace = true
actix-web.workspace = true
uuid.workspace = true
chrono.workspace = true
anyhow.workspace = true
dotenvy.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
futures-util.workspace = true
sqlx.workspace = true
validator = { version = "0.20", features = ["derive"] }
openssl = { version = "0.10.73", optional = true }
pbkdf2.workspace = true
tokio.workspace = true
const_format = "0.2.34"
build-utils = "0.1.0"

[dev-dependencies]
pretty_assertions.workspace = true
rstest.workspace = true
tokio = { workspace = true, features = ["test-util"] }
db_seeder = { path = "db_seeder" }
