services:
  db:
    container_name: projetario-db
    mem_reservation: 256mb
    image: postgres
    ports:
      - ${MAIN_DB_PORT}:5432
    environment:
      POSTGRES_USER: ${MAIN_DB_NAME}
      POSTGRES_PASSWORD: ${MAIN_DB_PASSWORD}
      POSTGRES_DB: ${MAIN_DB_NAME}
