[package]
name = "db_seeder"
version.workspace = true
edition.workspace = true

[dependencies]
sqlx.workspace = true
log.workspace = true
dotenvy.workspace = true
env_logger.workspace = true
config.workspace = true
tokio.workspace = true
pbkdf2.workspace = true
